name: Build APK dan Simpan ke Branch Release
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode dari Repositori
        uses: actions/checkout@v4

      - name: Cek Keberadaan File ZIP
        run: |
          echo "Memeriksa daftar file di repositori:"
          ls -la
          
      - name: Ekstrak File ZIP Proyek
        run: |
          # Perintah ini akan mengekstrak file ZIP apa pun yang Anda unggah
          unzip *.zip -d proyek_kamu
          echo "Isi folder proyek setelah diekstrak:"
          ls -la proyek_kamu

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Merakit APK Debug
        run: |
          cd proyek_kamu
          flutter pub get
          flutter build apk --debug

      - name: Siapkan Folder Pengiriman APK
        run: |
          mkdir -p output-apk
          cp proyek_kamu/build/app/outputs/flutter-apk/app-debug.apk output-apk/Aplikasi-AI-Samsung-A50.apk

      - name: Push APK ke Branch apk-release
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output-apk
          publish_branch: apk-release
          force_orphan: true
